### ISSUE TITLE
Fixes to installation instructions

### ISSUE THREAD

**Issue by thjsal** [sguillot/CompARE#49]
I installed the webapp and the database, but a few things needed to be fixed in the instructions before getting it working:

I installed `mysql-server` to my Ubuntu  20.04 machine using the instructions here:
https://www.digitalocean.com/community/tutorials/how-to-install-mysql-on-ubuntu-20-04

The quotation marks in the CompAre instructions seem incorrect (copy-pasting does not work for me). This line
`ALTER USER ‘root’@‘localhost' IDENTIFIED WITH mysql_native_password BY ‘pass1234’;`
should be 
`ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'pass1234';`

After that, if following the instructions, I get this error:
```
$ mysql -u root -p < scripts/database/database_compare3.sql
Enter password: 
ERROR 1046 (3D000) at line 22: No database selected
```

This is the way I fixed the problem:
```
$ mysql -u root -p
mysql> CREATE DATABASE compare3;
mysql> exit
$ mysql -u root -p --database=compare3 < scripts/database/database_compare3.sql
```

The next problem was encountered when I pip installed the packages from `requirementsDjango.txt`. I got this error: 
```
ERROR: Could not find a version that satisfies the requirement mysqlclient==2.1.1
ERROR: No matching distribution found for mysqlclient==2.1.1
```
This was solved by installing the missing package:
`sudo apt-get install libmysqlclient-dev`

In the end, I was still left with this error message (since there are currently conflicting requirements in  `requirementsDjango.txt`):
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
scipy 1.6.2 requires numpy<1.23.0,>=1.16.5, but you have numpy 1.24.3 which is incompatible.
```

However, running the web app server and opening it in a web browser seems to now work.

**Comment by sguillot** [comment]
- Thanks for pointing out the typos. I think the quotation mark ' were changed to ` at one point when I was copy-pasting instructions.
- The MySQL error must be due to a difference in version. I'll add your version as an alternative to create the database.
- I don't know why `pip install mysqlclient==2.1.1` did not work for you. I double-checked and this is the version I have on my condo compARE environment.
- Finally, I do not have scipy in my environment, so either removing scipy, but in the future if we need it, we'll need to define the compatible versions of numpy.

Thanks for trying the installation :-)
